### PR TITLE
Create ROS package for laser control

### PR DESCRIPTION
**Pull request by genkikondo**
Modularizes laser control into a separate ROS package/node (laser_control) with its own set of interface definitions (laser_control_interfaces). This makes it easier to maintain and test independently of the larger LRR project, and also becomes reusable in other ROS and non-ROS based projects.

1. Helios and Ether Dream implement the same interface. This interface is not dependent on ROS. This means that Helios and Ether Dream can be swapped interchangeably.
2. The laser_control_node.py ROS node is a thin wrapper around the above interface. This design makes it possible to utilize the laser DAC interfaces from both ROS and non-ROS projects.
3. When building with ROS, the native libraries under include/ are copied into share/laser_control/include, which makes them accessible via get_package_share_directory.

Services:
- /laser_control/list_dacs
- /laser_control/connect_to_dac
- /laser_control/set_color
- /laser_control/add_point
- /laser_control/remove_point
- /laser_control/clear_points
- /laser_control/play
- /laser_control/stop
- /laser_control/close

Example usage:
```
$ ros2 service call /laser_control/connect_to_dac laser_control_interfaces/srv/ConnectToDac "{idx: 0}"
$ ros2 service call /laser_control/add_point laser_control_interfaces/srv/AddPoint "{x: 100, y: 100}"
$ ros2 service call /laser_control/play laser_control_interfaces/srv/Play "{fps: 30, pps: 30000, transition_duration_ms: 0.5}"
```

### CODE REVIEW

**Comment by genkikondo** [comment]
Note: this isn't used yet in the main LRR package

**Comment by CA-rvinson** [comment]
This looks great, I am wondering about the pros and cons of having the laser control node be in it's own package entirely versus have it just be a separate node withing the main package. Do you have any strong opinions about this or any particular reasons you decided to move it over to a separate package

**Comment by genkikondo** [comment]
No strong opinions, but IMO it is cleaner to have all laser-related code in one package (include files don't intermix, can be released as a separate Python package and/or ROS package independent of LRR, interface definitions for laser control are also separate from others)

**Comment by CA-rvinson** [comment]
> No strong opinions, but IMO it is cleaner to have all laser-related code in one package (include files don't intermix, can be released as a separate Python package and/or ROS package independent of LRR, interface definitions for laser control are also separate from others and clear that it's only used for the laser)

What would you think about me doing the same thing for the realsense/camera module then? My main thought is that we might want to have consistency throughout the project about how we are handling each different 'subsystem' in the code.

**Comment by genkikondo** [comment]
I was actually starting to look into that now. I saw that the realsense node does a lot more than just capture camera frames - it does the image processing as well, like laser point detection and runner detection, so it's more closely tied to LRR. Ideally we'd have a camera node that just captures camera frames, then another node that does the image processing

**Comment by CA-rvinson** [comment]
I think the main issue is how we want to pass the color and depth information from the camera node to the processing node. I think it is cleaner, and a good goal, but I fear that having a ros2 message that contains all the frame data might be a bit much. I could be wrong though, and it could be a non-issue. I've also previously built out an input-output queue with numpy.memmap, but I think that's getting to complex for the current moment.   

Another question would be where we want to do the color image to depth image calculations. These need the intrinsic and extrinsic data from the camera, so if we want a processing node, we would have to pass this info from the camera on startup. 

I think the idea is good long term, I'm just not sure we want to take it on for now. A middle step could be creating a `perception` package that is responsible for everything currently in the realsense file, with the long term plan of creating an acquisition node and a processing node.

**Comment by genkikondo** [comment]
That's a good point, I'm not sure how DDS handles streaming of large amounts of data. There is a realsense ROS package that seems to have topics for image data (https://github.com/IntelRealSense/realsense-ros) but not sure how performance is.

I agree with you - it seems like too much overhead than it's worth to separate camera/perception right now. Though it would still be good to decouple the capture and perception logic at the node level.

**Comment by CA-rvinson** [comment]
I agree, and we can keep them coupled while still moving the node over to a separate package.

**Pull request merged**
